---
- name: Install phpbuild packages
  yum:
    name: "{{ phpbuild_packages }}"
    state: present

- name: Check phpbuild directory
  stat:
    path: "{{ phpbuild_destination}}"
  register: phpbuild_dest

- name: Install phpbuild
  git:
    repo: https://github.com/php-build/php-build.git
    dest: "{{ phpbuild_destination }}"
  when: not phpbuild_dest.stat.exists
